drop table dosare;

drop table date_studenti;

drop table registre;

drop table studenti;

drop table camere;

drop table camine;

drop table conducere;

drop table login;
drop table user_tables;

drop SEQUENCE CAMERE_ID_CAMERA_SEQ;
drop SEQUENCE CAMINE_ID_CAMIN_SEQ;
drop SEQUENCE CONDUCERE_ID_CONDUCERE_SEQ;
drop SEQUENCE DOSARE_ID_DOSAR_SEQ;
drop SEQUENCE REGISTRE_ID_REGISTRU_SEQ;
drop SEQUENCE STUDENTI_ID_STUDENT_SEQ;
drop SEQUENCE LOGIN_ID_LOG_SEQ;

drop TRIGGER CAMERE_ID_CAMERA_TRG;
drop TRIGGER CAMINE_ID_CAMIN_TRG;
drop TRIGGER CONDUCERE_ID_CONDUCERE_TRG;
drop TRIGGER DOSARE_ID_DOSAR_TRG;
drop TRIGGER REGISTRE_ID_REGISTRU_TRG;
drop TRIGGER STUDENTI_ID_STUDENT_TRG;
drop TRIGGER LOGIN_ID_LOG_TRG;
